// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzt9V52TiuooeR-eOJ19Yoq8A6sY5R80',
    appId: '1:324143336307:web:43ce5aee15e5b3b5cad306',
    messagingSenderId: '324143336307',
    projectId: 'petadoptionapp-e07ed',
    authDomain: 'petadoptionapp-e07ed.firebaseapp.com',
    storageBucket: 'petadoptionapp-e07ed.firebasestorage.app',
    measurementId: 'G-V3TBFT5FF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJhpYipfE2VUc1gDxeYLMWiyE2l0U3rk',
    appId: '1:324143336307:android:19faf9bd40bfd87ecad306',
    messagingSenderId: '324143336307',
    projectId: 'petadoptionapp-e07ed',
    storageBucket: 'petadoptionapp-e07ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxy9aZCsM0WLKcu9FH4JS1eLQbyoYvU4',
    appId: '1:324143336307:ios:45cb0e5a77eaf7fecad306',
    messagingSenderId: '324143336307',
    projectId: 'petadoptionapp-e07ed',
    storageBucket: 'petadoptionapp-e07ed.firebasestorage.app',
    iosClientId: '324143336307-8i5f2bbf9uu928fgml5hqess8e1iv6m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAdoptionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxy9aZCsM0WLKcu9FH4JS1eLQbyoYvU4',
    appId: '1:324143336307:ios:45cb0e5a77eaf7fecad306',
    messagingSenderId: '324143336307',
    projectId: 'petadoptionapp-e07ed',
    storageBucket: 'petadoptionapp-e07ed.firebasestorage.app',
    iosClientId: '324143336307-8i5f2bbf9uu928fgml5hqess8e1iv6m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAdoptionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzt9V52TiuooeR-eOJ19Yoq8A6sY5R80',
    appId: '1:324143336307:web:b57b284927360f51cad306',
    messagingSenderId: '324143336307',
    projectId: 'petadoptionapp-e07ed',
    authDomain: 'petadoptionapp-e07ed.firebaseapp.com',
    storageBucket: 'petadoptionapp-e07ed.firebasestorage.app',
    measurementId: 'G-71CWJMQNKE',
  );
}
